docling-project/docling

.github/workflows/checks.yml, README.md, poetry.lock, pyproject.toml
- Complete support for python 3.10
- Use v1.x version of the docling libraries
=> feat!: v1.0.0 release

poetry.lock, pyproject.toml
Following the strategy in https://python-poetry.org/docs/pyproject/#extras
=> fix: expose ocr as extra

.pre-commit-config.yaml, poetry.lock, pyproject.toml
- Properly add the extras
- Adding pre-commit for `poetry check` which would have noticed the issue beforehand
=> fix: add easyocr to main deps for valid extra

docling/backend/docling_parse_backend.py, examples/convert.py, poetry.lock, pyproject.toml
Uses our own docling_parse to reliably get PDF cells. To get page images, this backend uses pypdfium2.
=> feat: introducing docling_parse_backend

docling/backend/abstract_backend.py, docling/backend/docling_parse_backend.py, docling/backend/pypdfium2_backend.py, docling/datamodel/base_models.py, docling/pipeline/base_model_pipeline.py, docling/utils/export.py, poetry.lock, pyproject.toml, tests/verify_utils.py
This is a first round at improving the typing definition. It is not yet complete, but in the iteration we will have less to do.
It will also improve the stability of some tests.
=> test: improve typing definitions (part 1)

docling/cli/main.py, examples/convert.py, poetry.lock, pyproject.toml, tests/test_cli.py
=> feat: add docling cli

.github/workflows/cd.yml
=> chore: switch to gh apps user

docling/cli/main.py
=> feat: add URL support to CLI

examples/rag_langchain.ipynb, examples/rag_llamaindex.ipynb
=> chore: add RAG notebook titles

README.md
=> docs: document CLI, minor README revamp

poetry.lock, pyproject.toml
=> chore: move examples extras to respective group

README.md
=> docs: document chunking

examples/batch_convert.py, examples/custom_convert.py
- update examples to work in windows env
=> test: update examples

README.md, examples/rag_llamaindex.ipynb, poetry.lock, pyproject.toml
Also update docling-core minor version for fixed path format
**Checklist:**
=> docs: simplify LlamaIndex example using Docling extension

docling/models/tesseract_ocr_cli_model.py, tests/test_e2e_ocr_conversion.py, tests/verify_utils.py
=> fix: remove stderr from tesseract cli and introduce fuzziness in the text validation of OCR tests

docling/cli/main.py, docling/datamodel/document.py, docling/document_converter.py, docling/models/ds_glm_model.py, examples/batch_convert.py, examples/custom_convert.py, examples/export_figures.py, examples/export_multimodal.py, examples/export_tables.py, examples/minimal.py, examples/run_with_formats.py, tests/test_e2e_conversion.py, tests/test_e2e_ocr_conversion.py, tests/test_interfaces.py, tests/test_options.py
=> feat!: simplify conversion API

docling/models/tesseract_ocr_model.py
=> refactor: fix type of tesseractocr options

docling/document_converter.py
=> switch convert_all output type from Iterable to Iterator

docs/examples/rag_langchain.ipynb, docs/examples/rag_llamaindex.ipynb, docs/integrations/llamaindex.md, docs/overrides/main.html
=> update RAG examples and banner text

docs/use_docling.md, mkdocs.yml
=> docs: update chunking docs, rename page

README.md, docs/concepts/docling_document.md, docs/concepts/docling_format.md, docs/usage.md, docs/v2.md, mkdocs.yml
=> doc refinements

docs/concepts/docling_document.md
=> clean rendered content

.github/workflows/checks.yml
=> chore: run apt-get update before install

CONTRIBUTING.md
=> Fix Typo errors in CONTRIBUTING.md file

README.md, docs/examples/minimal.py, docs/index.md, docs/usage.md
=> chore: various minor docs fixes

docs/examples/export_figures.py
=> docs: add export with embedded images

docs/examples/batch_convert.py
=> docs: fix batch convert

docs/examples/rag_llamaindex.ipynb, docs/integrations/llamaindex.md
=> docs: update LlamaIndex docs for Docling v2

docling/backend/html_backend.py
=> restructure title fix

.github/workflows/cd-docs.yml, .github/workflows/cd.yml, .github/workflows/ci-docs.yml, README.md, docs/concepts/docling_document.md, docs/index.md
This PR enhances the README documentation to provide a clearer, more comprehensive overview of our tool's capabilities and supported formats. Key updates include:
1. **Multi-format Input/Output Support**:
- Added detailed information on all supported input formats (PDF, DOCX, PPTX, HTML, AsciiDoc, Markdown) and output formats (Markdown, JSON, YAML). This ensures users have a clear understanding of the tool's versatility across various document types.
2. **DoclingDocument Data Structure**:
- Highlighted the usage of the `DoclingDocument` data structure, which represents documents in a strongly typed Pydantic v2 structure. This emphasizes the structure’s robustness and type-safety, allowing for consistent and reliable document processing and integration.
These updates aim to enhance clarity …
=> chore: update the README to reflect all input/output format and highlight the DoclingDocument data-structure.

docs/integrations/llamaindex.md
=> docs: update LlamaIndex docs

docs/usage.md
=> docs: add explicit artifacts path example

docs/usage.md
=> docs: add artifacts-path param to CLI

README.md, docs/index.md
=> docs: add coming-soon section

Dockerfile
=> fix: Fix Dockerfile example copy

docling/backend/docling_parse_backend.py, docling/backend/docling_parse_v2_backend.py, docling/backend/pypdfium2_backend.py
occured -> occurred
**Checklist:**
=> chore: fix typo

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
=> chore: add issue templates

docling/backend/html_backend.py
=> fix: Added handling of code blocks in html with <pre> tag

docling/datamodel/settings.py
Potentially resolves https://github.com/DS4SD/docling/discussions/271
**Checklist:**
=> fix: Configure env prefix for docling settings

docs/integrations/data_prep_kit.md, docs/integrations/llamaindex.md, mkdocs.yml
=> docs: add Data Prep Kit integration

docling/models/ds_glm_model.py
If the language models are not needed, we should not download them all the time.
Fixes #262.
**Checklist:**
=> fix: skip glm model downloads

docling/cli/main.py
=> fix: reduce logging by keeping option for more verbose

docs/examples/hybrid_rag_qdrant.ipynb
=> chore: fix Qdrant notebook Colab link

.github/PULL_REQUEST_TEMPLATE.md, .mergify.yml
This change has been made by @dolfim-ibm from the Mergify merge protections editor.
See working example here: https://github.com/dolfim-ibm/ci-tester/pull/3
=> ci(Mergify): configuration update

poetry.lock
Update of dependencies in lock file. No change applied to the package.
**Checklist:**
=> chore: update lock of deps

.github/workflows/checks.yml, README.md, docling/cli/main.py, docling/document_converter.py, poetry.lock, pyproject.toml
Add support for python3.9.
Resolves #385 
**Checklist:**
=> fix: python3.9 support

.github/SECURITY.md, .github/actions/setup-poetry/action.yml, .github/workflows/cd.yml, .github/workflows/checks.yml, .github/workflows/pypi.yml, CITATION.cff, CONTRIBUTING.md, README.md
- Add downloads badge
- Add Security policy
- Update CI actions to new versions
- Add note about dependency licenses
**Checklist:**
=> chore: add downloads in README, security policy and update ci actions

docs/concepts/index.md, docs/index.md, docs/integrations/.template.md, docs/integrations/data_prep_kit.md, docs/integrations/docetl.md, docs/integrations/kotaemon.md, docs/integrations/llamaindex.md, docs/integrations/spacy.md, mkdocs.yml
=> docs: add DocETL, Kotaemon, spaCy integrations; minor docs improvements

docling/cli/main.py
Expose CLI options to visualize the model results.
**Checklist:**
=> fix(cli): expose debug options

docs/faq.md, mkdocs.yml
First round of FAQ in the docs.
**Checklist:**
=> docs: introduce faq section

docs/faq.md
=> docs: typo in faq

docling/cli/main.py, docling/datamodel/base_models.py, docling/datamodel/document.py, poetry.lock, pyproject.toml
=> chore: reuse DocumentStream from docling-core

docling/cli/main.py
Fix running the CLI on an input folder.
**Checklist:**
=> fix: folder input in cli

docling/backend/msword_backend.py
=> fix: Missing text in docx (t tag) when embedded in a table

docs/integrations/bee.md, docs/integrations/cloudera.md, docs/integrations/data_prep_kit.md, docs/integrations/docetl.md, docs/integrations/instructlab.md, docs/integrations/kotaemon.md, docs/integrations/llamaindex.md, docs/integrations/prodigy.md, docs/integrations/rhel_ai.md, docs/integrations/spacy.md, docs/integrations/txtai.md, mkdocs.yml
=> docs: document new integrations

docling/backend/msword_backend.py
Using style id instead of style names, which should be localization agnostic
Resolves #489 
**Checklist:**
=> feat(MS Word backend): Make detection of headers and other styles localization agnostic 

docling/backend/msword_backend.py
=> fix: Correcting DefaultText ID for MS Word backend

docling/models/ds_glm_model.py
=> fix: Do not import python modules from deepsearch-glm

mkdocs.yml
Fix broken link to the example with the accelerators.
**Checklist:**
=> docs: Fix the path to the run_with_accelerator.py example

docs/examples/rag_haystack.ipynb, mkdocs.yml
=> docs: add Haystack RAG example

docs/examples/rag_haystack.ipynb, docs/integrations/haystack.md, docs/integrations/rhel_ai.md, docs/integrations/vectara.md, mkdocs.yml
=> docs: document Haystack & Vectara support

mkdocs.yml
Adding link to RAG with Granite example.
**Checklist:**
=> docs: add link to rag with granite

docs/integrations/langchain.md
=> docs: add pointer to LangChain-side docs

docs/examples/translate.py, mkdocs.yml
=> docs: Example to translate documents

poetry.lock, pyproject.toml
=> fix: Update docling-parse-v2 backend version with new parsing fixes

docs/examples/rag_azuresearch.ipynb
=> docs: added markdown headings to enable TOC in github pages

docs/examples/rag_azuresearch.ipynb
=> docs: typo

README.md, docs/index.md
=> docs: updated the readme with upcoming features

docling/models/table_structure_model.py
=> fix: KeyError in tableformer prediction

.github/workflows/checks.yml, docs/examples/rapidocr_with_custom_models.py, mkdocs.yml
Documentation example how to use RapidOCR with custom models for english.
**Checklist:**
=> docs: Introduce example with custom models for RapidOCR

docling/cli/main.py, docling/models/base_model.py, docling/models/code_formula_model.py, docling/pipeline/base_pipeline.py
feat(CLI): Expose picture classifier.
fix: Reduce batch size for some models.
**Checklist:**
=> fix: enrichment models batch size and expose picture classifier

docling/backend/md_backend.py, tests/data/groundtruth/docling_v2/nested.md.md, tests/data/md/nested.md, tests/test_backend_markdown.py, tests/test_data_gen_flag.py
=> fix(markdown): handle nested lists

docling/cli/main.py, docling/datamodel/pipeline_options.py, docling/exceptions.py, docling/models/picture_description_api_model.py, docling/pipeline/standard_pdf_pipeline.py, docs/examples/pictures_description_api.py, docs/usage.md
Implement the new design for allowing calls to remote services as described in https://github.com/DS4SD/docling/discussions/768.
Resolves #840.
**Checklist:**
=> feat: Introduce the enable_remote_services option to allow remote connections while processing

docs/examples/pictures_description_api.py, mkdocs.yml
=> docs: Examples for picture descriptions

Dockerfile
Update the models download in the example Dockerfile and provide a full offline example.
**Checklist:**
=> docs: update example Dockerfile with download CLI

docling/cli/models.py
=> feat(cli): add option for downloading all models, refine help messages

docs/examples/hybrid_chunking.ipynb, docs/faq.md
Improving docs upon feedback in #1072.
=> docs: improve docs on token limit warning triggered by HybridChunker

docs/usage/index.md
=> docs: add description of DOCLING_ARTIFACTS_PATH env var

docling/cli/main.py
=> fix(CLI): fix help message for abort options

.github/SECURITY.md, .github/workflows/ci-docs.yml, .github/workflows/ci.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, docling/cli/models.py, docling/models/ocr_mac_model.py, docling/models/tesseract_ocr_model.py, docs/concepts/docling_document.md, docs/examples/backend_xml_rag.ipynb, docs/examples/hybrid_chunking.ipynb, docs/examples/pictures_description.ipynb, docs/examples/rag_azuresearch.ipynb, docs/examples/rag_haystack.ipynb, docs/examples/rag_langchain.ipynb, docs/examples/rag_llamaindex.ipynb, docs/examples/rag_weaviate.ipynb, docs/examples/retrieval_qdrant.ipynb, docs/faq/index.md, docs/index.md, docs/integrations/haystack.md, docs/integrations/langchain.md, mkdocs.yml, pyproject.toml, tests/data/groundtruth/docling_v2/word_tables.docx.html, tests/test_input_doc.py
=> chore: move to docling-project org

docs/usage/enrichments.md
docs: fix spelling of picture in usage)
=> docs: fix spelling of picture in usage

README.md, docs/integrations/apify.md, mkdocs.yml
=> docs: move apify to docs

docling/backend/msword_backend.py
Resolves #1192 
**Checklist:**
=> fix(msword): Fixing function return in equations handling

docling/backend/docling_parse_v4_backend.py
Resolves #1181 
**Checklist:**
=> fix: Determine correct page size in DoclingParseV4Backend

docling/backend/html_backend.py, tests/data/groundtruth/docling_v2/example_01.html.json, tests/data/groundtruth/docling_v2/example_01.html.md, tests/data/groundtruth/docling_v2/example_02.html.json, tests/data/groundtruth/docling_v2/example_02.html.md, tests/data/groundtruth/docling_v2/example_03.html.json, tests/data/groundtruth/docling_v2/example_03.html.md, tests/data/groundtruth/docling_v2/mixed.md.md, tests/data/groundtruth/docling_v2/unit_test_01.html.json, tests/data/groundtruth/docling_v2/unit_test_01.html.md, tests/data/groundtruth/docling_v2/wiki_duck.html.json, tests/data/groundtruth/docling_v2/wiki_duck.html.md, tests/test_backend_html.py
=> fix(html): fix HTML parsed heading level

docling/backend/mspowerpoint_backend.py
=> fix(pptx): check if picture shape has an image attached

docs/concepts/plugins.md, mkdocs.yml
=> docs: add plugins docs

docling/backend/html_backend.py
This change ensures that the content contained in the code tag is displayed correctly when the HTML is converted.
Resolves #1302 
**Checklist:**
=> feat: handle <code> tags as code blocks

docling/datamodel/pipeline_options.py, docling/models/picture_description_base_model.py
Implement the use of `bitmap_area_threshold` for the picture-description process
**Checklist:**
=> fix: Implement PictureDescriptionApiOptions.bitmap_area_threshold

docling/backend/msword_backend.py
This PR fixes an issue when handling pictures in the Word parser backend.
Resolves #1353
=> fix(docx): declare image_data variable when handling pictures

CITATION.cff
Repository was moved to docling-project/docling, so adjust the URL.
**Checklist:**
=> chore: Update repository URL in CITATION.cff

poetry.lock, pyproject.toml
Resolves #1372 
**Checklist:**
=> fix(deps): widen typer upper bound

docs/installation/index.md
Add a Informational Notes when Install docling in Intel MacOS especially uv
Resolves #1351
**Checklist:**
=> docs: Add Notes for Installing in Intel macOS

CONTRIBUTING.md
=> docs: Add testing in the docs

.github/SECURITY.md
=> docs(security): more statements about secure development

.github/codecov.yml, .github/workflows/checks.yml
- fix wrong argument in codecov
- fix indentation error in codecov yaml file
=> fix(codecov): fix codecov argument and yaml file

README.md, docs/index.md
=> docs: Add OpenSSF Best Practices badge

poetry.lock, pyproject.toml
=> chore: update locked deps

docs/examples/rag_milvus.ipynb, mkdocs.yml
This PR adds a Jupyter notebook tutorial demonstrating how to build a Retrieval-Augmented Generation (RAG) pipeline using **Milvus** as the vector database and **Docling** for document handling. The tutorial also integrates **OpenAI** APIs for both embedding generation and language model inference.
-  **Milvus vector store integration** for document indexing and retrieval
-  **Docling** used for parsing and handling document structures
-  **OpenAI Embedding API** for vector generation
-  **OpenAI Chat API** (GPT) for generating responses
- Document parsing and embedding via Docling + OpenAI
- Milvus setup and connection
- Collection creation and index definition
- Vector insertion and top-k ANN retrieval
- Prompt generation and LLM response using OpenAI Chat API
- Ensure that API keys for …
=> feat: add tutorial using Milvus and Docling for RAG pipeline

docs/usage/index.md
This small PR fixes the `supported_formats.md` reference. Relevant page: https://docling-project.github.io/docling/usage/
**Checklist:**
=> docs: update supported formats guide

docling/backend/md_backend.py, docling/backend/msword_backend.py, docling/backend/xml/jats_backend.py, docling/backend/xml/uspto_backend.py, docling/cli/main.py, docling/models/table_structure_model.py, docling/models/tesseract_ocr_model.py, docs/examples/backend_xml_rag.ipynb, docs/examples/hybrid_chunking.ipynb, docs/examples/pictures_description.ipynb, docs/examples/rag_milvus.ipynb, docs/examples/rag_weaviate.ipynb, docs/faq/index.md, docs/v2.md
=> chore: typo fix

poetry.lock
Relevant updates:
- h11 vulnerability
- torch 2.7 update
**Checklist:**
=> chore: update dependencies in lock file

docling/datamodel/document.py
fix got file mime error
**Checklist:**
=> fix: mime error in document streams

docling/cli/models.py, docling/utils/model_downloader.py
=> fix: add smoldocling in download utils

docling/datamodel/settings.py, tests/test_settings_load.py
Resolves #1550
Fix loading nested settings provided via environment variables with pydantic_settings
**Checklist:**
=> fix(settings): fix nested settings load via environment variables

docling/datamodel/pipeline_options.py, docling/models/api_vlm_model.py, docling/models/picture_description_api_model.py
Resolves #1522 
**Checklist:**
=> feat: Improve parallelization for remote services API calls

tests/verify_utils.py
=> test: ensure utf-8 in test data utils

docs/examples/batch_convert.py, docs/examples/custom_convert.py, docs/examples/develop_formula_understanding.py, docs/examples/develop_picture_enrichment.py, docs/examples/export_figures.py, docs/examples/export_multimodal.py, docs/examples/export_tables.py, docs/examples/full_page_ocr.py, docs/examples/pictures_description_api.py, docs/examples/run_with_accelerator.py, docs/examples/tesseract_lang_detection.py, docs/examples/translate.py, docs/examples/vlm_pipeline_api_model.py
Updating the examples for running both from the root folder or directly from the subfolder.
Supersede https://github.com/docling-project/docling/pull/1561.
**Checklist:**
=> docs: support running examples from root or subfolder

.github/workflows/checks.yml, README.md, docs/examples/minimal_asr_pipeline.py, docs/index.md, mkdocs.yml
Update readme and add asr example
**Checklist:**
=> docs: update readme and add ASR example

docling/models/picture_description_vlm_model.py
Resolves https://github.com/docling-project/docling/issues/1447 https://github.com/docling-project/docling/issues/1854
**Checklist:**
=> fix: Secure torch model inits with global locks

docs/usage/vision_models.md
=> docs: Fix typos

docling/utils/layout_postprocessor.py
=> fix: Keep formula clusters also when empty

docs/integrations/arconia.md, mkdocs.yml
=> docs: Add Arconia integration

.github/workflows/pr-reminders.yml
This is an automatic check of all PRs which require a review approval for running the CI.
**Checklist:**
=> chore: PR approval reminder

docs/examples/translate.py
Some fixes for a couple of issues encountered while running through the translation example:
1. Fix exception when translating documents with tables:
```
Traceback (most recent call last):
File "/Users/shikharbhardwaj/Documents/dev/spike/ai-playground/engels-bot/translate.py", line 174, in <module>
File "/Users/shikharbhardwaj/Documents/dev/spike/ai-playground/engels-bot/translate.py", line 167, in main
elif isinstance(element, TableItem):
File "/Users/shikharbhardwaj/venvs/ai-playground/lib/python3.13/site-packages/pydantic/main.py", line 991, in __getattr__
raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'TableItem' object has no attribute 'text'
```
2. Use the file name instead of full path for naming output files.
3. Run `main` when …
=> fix: translation example

docs/examples/extraction.ipynb
=> docs: Document VLM support requirement in extraction example

README.md, docs/index.md, docs/usage/mcp.md, mkdocs.yml
Add instructions for using Docling with MCP to README as it's a great way for developers to quickly start experimenting with Docling
**Checklist:**
=> docs: Add instructions for using Docling with MCP to README

docs/examples/batch_convert.py, docs/examples/compare_vlm_models.py, docs/examples/custom_convert.py, docs/examples/develop_formula_understanding.py, docs/examples/develop_picture_enrichment.py, docs/examples/enrich_doclingdocument.py, docs/examples/export_figures.py, docs/examples/export_multimodal.py, docs/examples/export_tables.py, docs/examples/full_page_ocr.py, docs/examples/inspect_picture_content.py, docs/examples/minimal.py, docs/examples/minimal_asr_pipeline.py, docs/examples/minimal_vlm_pipeline.py, docs/examples/pictures_description_api.py, docs/examples/rapidocr_with_custom_models.py, docs/examples/run_with_accelerator.py, docs/examples/run_with_formats.py, docs/examples/tesseract_lang_detection.py, docs/examples/translate.py, docs/examples/vlm_pipeline_api_model.py
update out of date imports and calls, add guiding text for example clarity and flow
**Checklist:**
=> docs: Describe examples

docs/stylesheets/extra.css, mkdocs.yml
1. Updated the docs color scheme
3. docs(styling): update color scheme
=> docs(styling): update color scheme

docling/cli/main.py, docling/datamodel/pipeline_options_vlm_model.py, docling/datamodel/vlm_model_specs.py, docling/models/base_model.py, docling/models/utils/hf_model_download.py, docling/models/vlm_models_inline/hf_transformers_model.py, docling/models/vlm_models_inline/mlx_model.py, docling/models/vlm_models_inline/vllm_model.py
=> fix: Update Transformers & VLLM inference code, CLI and VLM specs

docs/stylesheets/extra.css, mkdocs.yml
Issue resolved by this Pull Request:
Resolves https://github.com/docling-project/docling/issues/2363
Resolves #2362
Description of changes:
This PR fix the color scheme of docs for light mode and dark mode 
**Checklist:**
=> fix(docs): fixed the color scheme

docs/examples/rag_mongodb.ipynb
Updated the code 
**Checklist:**
=> docs: Add MongoDB + VoyageAI
