docling-project/docling

- docling/backend/pypdfium2_backend.py
[`PdfDocument`](https://pypdfium2.readthedocs.io/en/stable/python_api.html#pypdfium2._helpers.document.PdfDocument) should do accept strings, paths, bytes and byte streams. If not, please file a bug report.
> pypdfium2: just forward input to PdfDocument directly

- docling/models/table_structure_model.py
- examples/convert.py
- Fixed scaling transformation for table cell bounding boxes when using do_cell_matching = False
- Corrected `examples/convert.py` with appropriate parameter, for good quality example conversion
> Fixes for correct text extraction for table cells

- poetry.lock
- pyproject.toml
This is to align with `opencv-python-headless` on all platforms.
> fix: Update docling-ibm-models to v1.1.2

- README.md
- docling/datamodel/base_models.py
- docling/datamodel/document.py
- docling/document_converter.py
- docling/models/ds_glm_model.py
- examples/batch_convert.py
- examples/custom_convert.py
- examples/export_figures.py
- fields `output` and `assembled` need not be optional
- introduced "synonym" `ConversionResult` for `ConvertedDocument` and deprecated the latter
> fix: refine conversion result

- poetry.lock
- pyproject.toml
Update dependencies to the [docling-ibm-models v1.1.3](https://github.com/DS4SD/docling-ibm-models/releases/tag/v1.1.3).
- Fix table cell overlap removal
- Fix model warnings
> fix: table cells overlap and model warnings

- docling/cli/main.py
> fix: fix OCR setting for pypdfium, minor refactor

- docling/datamodel/document.py
- poetry.lock
- pyproject.toml
- tests/data/2203.01017v2.md
- tests/data/2206.01062.md
- tests/data/2305.03393v1-pg9.md
- tests/data/2305.03393v1.md
- tests/data/redp5110.md
- tests/data/redp5695.md
> feat: add figure in markdown

- docling/document_converter.py
**Description of Changes**:
This PR ensures that the PDF backend resources are properly cleaned up in case of failures by moving the resource cleanup into a `finally` block.
Resolves #127
**Checklist:**
>  fix: ensure PDF backend resources are cleaned up in case of failures

- poetry.lock
- pyproject.toml
Pandas was [already used](https://github.com/DS4SD/docling/blob/0ffc1708d2532158d82ae1d4cd7c30881297a0a5/docling/models/tesseract_ocr_cli_model.py#L94) but not explicitly tracked as a direct dependency.
Version selected for compatibility with `ibm-watsonx-ai`:
```
pip install ibm-watsonx-ai "pandas>=2.2.2,<3.0.0"
[...]
ERROR [...]
The conflict is caused by:
The user requested pandas<3.0.0 and >=2.2.2
ibm-watsonx-ai 1.1.14 depends on pandas<2.2.0 and >=0.24.2
[...]
```
**Checklist:**
> chore: explicitly manage pandas dependency

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- README.md
- docs/concepts/docling_document.md
- docs/usage.md
- docs/use_docling.md
- docs/v2.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
> docs: add use docling

- .github/workflows/ci.yml
Adding the `synchronize` event, the CI will run on forks. Additionally, with some `if: ` we avoid running the jobs twice, when we are not on a fork.
**Checklist:**
> ci: run ci also on forks

- docling/datamodel/document.py
- docling/models/ds_glm_model.py
- tests/verify_utils.py
> fix: fix legacy doc ref

- docling/datamodel/pipeline_options.py
- docling/models/base_ocr_model.py
- tests/test_options.py
New option `pipeline_options.ocr_options.coverage_threshold` which allows to skip OCR on small pictures.
**Checklist:**
> feat: add coverage_threshold to skip OCR for small images

- docling/datamodel/document.py
- tests/test_input_doc.py
> fix: set valid=false for invalid backends

- .github/workflows/cd.yml
- .github/workflows/ci.yml
This change will stop running the CD pipeline on every merge to main. Instead, we will trigger it manually, which allows to group multiple changes in a single release.
**Checklist:**
> chore: make auto-release on request

- docling/backend/html_backend.py
Fixes for HTML backend, corrects issue with improper extraction of nested text for lists
**Checklist:**
> fix: HTML backend, fixes for Lists and nested texts

- docling/backend/md_backend.py
- Hanging MD backend conversion with long underscore symbols sequence Issue fixed with this PR
- Fixed handle last hanging inline text element in the document
**Checklist:**
> fix: [Optional] MD backend, handling long sequence of unescaped underscore chars

- docling/backend/html_backend.py
- docling/backend/msword_backend.py
- tests/test_backend_html.py
- tests/test_backend_msword.py
- HTML backend:
- used `add_heading` instead of `add_text` for headings
- did minor refactoring
- DOCX backend:
- passed actual level to `add_heading` (explicitly setting it to 1 if not identifiable)
- did minor refactoring
**Checklist:**
> fix: fix heading levels for DOCX & HTML

- docling/document_converter.py
- docs/examples/run_with_formats.py
This PR allows users to initialize the pipelines on request. For example, this is needed when we need control on when artifacts are downloaded.
**Checklist:**
> fix: allow to explicitly initialize the pipeline

- docling/cli/main.py
- docling/datamodel/pipeline_options.py
- docs/usage.md
With this PR we expose the more options in the CLI, i.e. which PDF backend and which table model.
Note: I had to change the enum, because it was serializing to values "1" and "2". Instead of introducing yet another Enum, I think we can be more explicit in the existing one.
**Checklist:**
> feat: pdf backend, table mode as options and artifacts path

- docs/usage.md
Fixed a one-word spelling error in `usage.md` by changing invidual to it's correct form of: individual.
Resolves #215 
**Checklist:**
> docs: correct spelling of 'individual'

- Dockerfile
- docs/examples/custom_convert.py
Fixing old code snippet of docling v1 both in the custom_convert.py example and the Dockerfile.
Resolves #213
https://github.com/DS4SD/docling/issues/213
**Checklist:**
> docs: update custom convert and dockerfile

- pyproject.toml
> chore: update pyproject.toml metadata

- README.md
- docs/index.md
> docs: update badges & credits

- docling/models/tesseract_ocr_model.py
Add an explicit check in `TesseractOcrModel` if tesserocr languages have been actually loaded. Otherwise raise an Exception
**Checklist:**
> fix(tesserocr): Raise Exception if tesserocr has not loaded any languages

- docling/models/easyocr_model.py
- Implement support for the `EasyOcrOptions.use_gpu` parameter.
- Disable the GPU for EasyOCR if MPS is detected.
**Checklist:**
> fix(EasyOcrModel): Control if the EasyOcrModel will run on GPU based on the pipeline options and the presence of MPS

- docling/models/easyocr_model.py
- docs/examples/custom_convert.py
This PR allows the usage of Metal Performance Shaders (MPS) accelerators on Mac for EasyOCR.
EasyOCR has already an internal device choice, see https://github.com/JaidedAI/EasyOCR/blob/master/easyocr/easyocr.py#L72.
Since this is triggered only with the argument `gpu=True`, we should not overwrite it.
Some users encounter issues like the following (specially in GitHub CI):
```
2024-11-08T03:46:47.8493970Z E           RuntimeError: MPS backend out of memory (MPS allocated: 8.00 MB, other allocations: 16.00 KB, max allowed: 7.93 GB). Tried to allocate 256 bytes on shared pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
```
Unfortunately, this is because GitHub runners are not able to virtualize the MPS accelerators (see …
> fix: allow mps usage for easyocr

- docling/backend/mspowerpoint_backend.py
We were not looking into powerpoint groups, hence grouped elements were ignored, this PR fixes that.
Resolves #292 
**Checklist:**
> fix: Added handling of grouped elements in pptx backend

- docling/cli/main.py
- docling/datamodel/pipeline_options.py
- docling/models/base_ocr_model.py
- docling/models/easyocr_model.py
- docling/models/tesseract_ocr_cli_model.py
- docling/models/tesseract_ocr_model.py
- docs/examples/full_page_ocr.py
- mkdocs.yml
- tests/test_e2e_ocr_conversion.py
- tests/verify_utils.py
In certain occasions the user may want to force a full page OCR and ignore the text contained in a programmatic PDF (see issue #185).
This PR introduces the parameter `OcrOptions.force_full_page_ocr` that implements this feature. 
Please check this example that demonstrates how to force OCR: https://github.com/DS4SD/docling/blob/force_ocr/docs/examples/full_page_ocr.py
Resolves #185 
**Checklist:**
> feat(OCR): Introduce the OcrOptions.force_full_page_ocr parameter that forces a full page OCR scanning

- docs/usage.md
Fixed parameter in of DocumentStream in usage.md.
Resolves #331
**Checklist:**
> docs: fix parameter in usage.md

- docling/cli/main.py
- docling/datamodel/pipeline_options.py
This PR adds the `--ocr-lang` option to the docling CLI. Multiple languages are specified as a comma-separated list.
Resolves #255, #225
**Checklist:**
> feat: expose ocr-lang in CLI

- docs/v2.md
Minor fix - documentation example was missing parentheses.
> docs: fixed typo in v2 example v2

- docs/examples/advanced_chunking_with_merging.ipynb
- docs/examples/rag_langchain.ipynb
Some key differences between this proposed chunking notebook and the one in `advanced_chunking.ipynb`:
1. This one merges chunks that have the same headings and captions (e.g., adjacent paragraphs within the same section).
2. This one splits on doc_items such as elements of an itemized list _before_ trying to apply generic text splitting.  This results in chunks that respect the begin and end of the list items more often.
3. This one uses the `DoclingDocument.name` as the title of the document instead of assuming that the title will be in the headers.  That's probably not a great idea going forward though because in the near future the extracted title _will_ be in the headers.  The `DoclingDocument.name` comes from document metadata and sometimes also reflects the title but is often not …
> Sample chunking notebook that includes merging, etc.

- docling/document_converter.py
We have a small bug which is not propagating the document limits `max_num_pages` and `max_file_size` to the actual converter.
**Checklist:**
> fix: propagate document limits to converter

- poetry.lock
- pyproject.toml
It seems the new Pydantic 2.10.0 release (16h ago).
Downgrading Pydantic works, and it seems the approach taken by many libraries. See https://github.com/run-llama/llama_index/issues/17016.
Resolves #406
**Checklist:**
> fix: force pydantic < 2.10.0

- docling/datamodel/pipeline_options.py
- docs/api_reference/docling_document.md
- docs/api_reference/document_converter.md
- docs/api_reference/pipeline_options.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
Generate the automatic API documentation for the main Docling components and pipeline options.
Adding more docstrings, specially in the document_converter, will enhance the result.
**Checklist:**
> docs: add automatic api reference

- docling/cli/main.py
- docling/datamodel/document.py
The new `resolve_source_to_x()` functions allow to manage the temporary store or to avoid it completely via document streams.
**Checklist:**
> fix: use new resolve_source_to_x functions to avoid tempfile leftovers

- docling/models/tesseract_ocr_cli_model.py
- Make sure that the `tesseract_ocr_cli_model.py` does not open the png image file twice (before it was opened once with `tempfile.NamedTemporaryFile`  and again by passing the file name rather than the file object itself to `high_res_image.save`;
- Ensure that `_run_tesseract` is executed after the file is no longer open by python. This otherwise results in a "PermissionError: [Errno 13] Permission denied" error on Windows.
(Replaces https://github.com/DS4SD/docling/pull/430)
> fix: PermissionError when using tesseract_ocr_cli_model

- poetry.lock
- pyproject.toml
After updating the docling packages with a wider numpy range (https://github.com/DS4SD/docling-ibm-models/releases/tag/v2.0.7, https://github.com/DS4SD/deepsearch-glm/releases/tag/v0.26.2), we can update the docling lock file.
**Checklist:**
> chore: update numpy lock

- poetry.lock
- pyproject.toml
This PR allows the new version of pydantic 2.10.3, but limits the intermediate broken releases.
**Checklist:**
> fix: restore pydantic version pin after fixes

- README.md
- docling/cli/main.py
- docling/datamodel/base_models.py
- docs/index.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
1. Added the HTML export to CLI
```sh
poetry run docling --from pdf --to html <filename: 2206.01062v1.pdf>
```
> fix: Enable HTML export in CLI and add options for image mode  

- .github/mergify.yml
We have to patch the default mergify CI logic in order to allow for major releases.
**Checklist:**
> ci: allow ! in conventionalcommits

- docling/cli/main.py
- docling/datamodel/base_models.py
- docling/datamodel/pipeline_options.py
The `auto()` enum generates only number values which are not easy to interpret and depend on the other inside the enum.
By setting the value explicitly and moving a few enum higher up, we make the downstream usage in other projects easier.
**Checklist:**
> fix: make enum serializable with human-readable value

- docling/models/rapid_ocr_model.py
Resolves https://github.com/DS4SD/docling/issues/547
**Checklist:**
> fix: Handle no result from RapidOcr reader

- docling/cli/main.py
- docling/datamodel/pipeline_options.py
- docling/pipeline/base_pipeline.py
Signed-off-by: Abhishek Kumar <abhishekrocketeer@gmail.com>
Testing:
(.venv) mario@Abhisheks-MacBook-Air docling % docling https://arxiv.org/pdf/2206.01062 --document-timeout=10 --verbose INFO:docling.document_converter:Going to convert document batch... INFO:docling.pipeline.base_pipeline:Processing document 2206.01062v1.pdf WARNING:docling.pipeline.base_pipeline:Document processing time (24.555 seconds) exceeded the specified timeout of 10.000 seconds INFO:docling.document_converter:Finished converting document 2206.01062v1.pdf in 36.29 sec. WARNING:docling.cli.main:Document /var/folders/d7/dsfkllxs0xs8x2t4fcjknj4c0000gn/T/tmpl6p08u5i/2206.01062v1.pdf failed to convert. INFO:docling.cli.main:Processed 1 docs, of which 1 failed INFO:docling.cli.main:All documents were converted in 36.29 …
> feat: Add timeout limit to document parsing job. DS4SD#270

- docling/datamodel/pipeline_options.py
- docling/models/easyocr_model.py
Adding recog_network parameter of EasyOCR to allow users use their own custom recognition model. 
This one I have apply pre-commit hook `pre-commit run --all-files` so I hope it able to merge now. 
Resolves #602 #604 
**Checklist:**
> feat: Add Easyocr parameter recog_network

- tests/test_cli.py
This PR addresses the following fix:
The regression test in `tests/test_cli.py` checks if a docling conversion is successful by invoking the command line.
The execution creates a markdown file `2305.03393v1-pg9.md` in the current directory that is not source-controlled. Since it is not necessary to persist this file, this feature is about refactoring the test to ensure that the generated file exists in a temporary directory. After the test finishes, the temporary directory with the markdown file gets automatically deleted.
**Checklist:**
> test: generate file from CLI in a temporary directory

- docs/examples/rag_weaviate.ipynb
- mkdocs.yml
**Description**
Added a new recipe for using Weaviate with Docling for RAG workflows. The notebook demonstrates how to:
* Parse machine learning papers from arXiv using Docling 
* Perform hierarchical chunking of the documents using Docling 
* Generate text embeddings with OpenAI 
* Perform RAG over the articles using Weaviate
Original link for the notebook can be found [here](https://github.com/weaviate/recipes/blob/main/integrations/data-platforms/ibm/docling/rag_over_pdfs_docling_weaviate.ipynb).
**Checklist:**
> docs: add Weaviate RAG recipe notebook

- docs/integrations/opencontracts.md
- mkdocs.yml
**Description:**
Added [OpenContracts](http://localhost:3000/extracts) to the integration docs. OpenContracts is a bulk document data extraction and annotation platform. We support token-level text annotations as well as relationships between annotations. We've added Docling as one of our supported document parsers and are using it to parse PDFs, incorporating your text annotations and chunks ("relationships" in our ontology) for retrieval and analysis. 
**Checklist:**
> docs: Add OpenContracts as an integration

- docling/cli/main.py
- docling/datamodel/document.py
- docling/document_converter.py
propagate header argument from resolve_source_to_stream to cli and convert/convert_all
Resolves #634
**Checklist:**
> feat: added http header support for document converter and cli

- docs/reference/docling_document.md
The [docstring_style](https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_style) is needed to improve the parsing of the function parameters.
**Checklist:**
> docs: specify docstring types

- docling/backend/docling_parse_backend.py
- docling/backend/docling_parse_v2_backend.py
- docling/backend/pypdfium2_backend.py
- docling/datamodel/pipeline_options.py
- docling/models/base_ocr_model.py
This introduces multiple changes to address problems with partially failing content in scanned documents.
- The code for detection of OCR rectangles now merges almost-connected, nearby bitmap rectangles into one
- OCR rectangles are not dropped individually if they don't pass the size threshold, only if the sum of all OCR rectangles falls below the size threshold
- EasyOCR confidence lowered to 0.5 (from 0.65) for better recall  
Resolves #641 and others
**Checklist:**
> fix: Improve OCR results, stricten criteria before dropping bitmap areas 

- docling/backend/docling_parse_backend.py
- docling/backend/docling_parse_v2_backend.py
- docling/backend/pypdfium2_backend.py
- docling/datamodel/base_models.py
- docling/models/base_model.py
- docling/models/page_assemble_model.py
- docling/pipeline/base_pipeline.py
- docling/pipeline/standard_pdf_pipeline.py
- docs/examples/develop_formula_understanding.py
The PR allows to run enrichment models which interact with the page backend. For example, this can be used to retrieve the image of a document item without the need of storing actual image in the final document.
The new base `GenericEnrichmentModel` allows to achieve it by maintaining backwards compatibility.
_Note: the example file `docs/examples/develop_formula_understanding.py` is just testing the interface we don't have to include it in the final version._
cc @Matteo-Omenetti 
**Checklist:**
> refactor: allow the usage of backends in the enrich models and generalize the interface

- docs/examples/custom_convert.py
fix[docs/examples/custom_convert.py]: Added the missing AcceleratorDevice and AcceleratorOptions functions in the imports and changed Device in the code to the correct AcceleratorDevice.
**Checklist:**
- [ x] Documentation has been updated, if necessary.
- [ x] Examples have been added, if necessary.
- [ x] Tests have been added, if necessary.
> docs: fix correct Accelerator pipeline options in docs/examples/custom_convert.py

- .github/workflows/docs.yml
This PR adds an open-source action to generate necessary llms files to the docs as per the standard.
- Added `demodrive-ai/llms-txt-action@v1` action
- Added `--dirty` flag in gh-deploy to keep the generated files.
Resolves #699 
**Checklist:**
> ci: added action to generate llms.txt

- docs/concepts/chunking.md
- docs/v2.md
Fixing some broken links between docs pages (from mkdocs warnings).
**Checklist:**
> docs: fix links between docs pages

- .github/workflows/checks.yml
- docling/models/tesseract_ocr_model.py
- tests/test_e2e_ocr_conversion.py
Add language-agnostic OCR option for TesseractOcr module. It is invoked when the language option is set to `['auto']`. For more context, see the discussion: https://github.com/DS4SD/docling/discussions/640
Please let me know what you think.
**Checklist:**
> feat: add "auto" language for TesseractOcr

- docs/examples/rag_azuresearch.ipynb
fix minor typos
**Checklist:**
- [x ] Documentation has been updated, if necessary.
- [x ] Examples have been added, if necessary.
- [x ] Tests have been added, if necessary.
> docs: super minor typos

- docling/backend/abstract_backend.py
- docling/backend/json/docling_json_backend.py
- docling/datamodel/base_models.py
- docling/datamodel/document.py
- docling/document_converter.py
- tests/test_backend_docling_json.py
- tests/test_input_doc.py
> feat: add Docling JSON ingestion

- docling/models/tesseract_ocr_cli_model.py
- docling/models/tesseract_ocr_model.py
- docling/utils/ocr_utils.py
- docs/examples/tesseract_lang_detection.py
- mkdocs.yml
- tests/test_e2e_ocr_conversion.py
Introduce automatic language detection for the `TesseractOcrCliModel`.
The language detection mode is enabled when `lang == "auto"`
**Checklist:**
> feat: Introduce automatic language detection in TesseractOcrCliModel

- docling/backend/xml/uspto_backend.py
- docs/examples/backend_xml_rag.ipynb
- docs/usage.md
- mkdocs.yml
- tests/test_backend_msexcel.py
- tests/test_backend_patent_uspto.py
- tests/test_backend_pubmed.py
- Add documentation on supported formats and conversion backends
- Add a notebook example on custom XML formats (USPTO and PMC)
- Remove unnecessary imports on tests
- Remove unnecessary `type-ignore` marks
**Checklist:**
> docs: description of supported formats and backends

- poetry.lock
The PR updates the dependencies in the lock file, e.g. `docling-parse`.
This has no impact on the distributed releases, but it will change the version of the dependencies used in the CI tests.
**Checklist:**
> chore: update deps in lockfile

- docling/datamodel/pipeline_options.py
- docling/models/rapid_ocr_model.py
- Added `rec_keys_path` to `RapidOcrOptions` to align with RapidOCR's capability to use custom character dictionaries.
- Passed `rec_keys_path` to `RapidOcrModel` initialization, ensuring the recognition model can load the correct dictionary (e.g., for Latin characters).
**Checklist:**
> feat(ocr): expose `rec_keys_path` in RapidOcrOptions to support custom dictionaries

- docling/cli/main.py
Adding platform info based on [platform.platform()](https://docs.python.org/3.9/library/platform.html#platform.platform), aiming to getting OS, OS version, and architecture out of the box with `docling --version` (e.g. for debugging issues etc.)
> feat: add platform info to CLI version printout

- docling/backend/html_backend.py
- tests/data/groundtruth/docling_v2/example_05.html.itxt
- tests/data/groundtruth/docling_v2/example_05.html.json
- tests/data/groundtruth/docling_v2/example_05.html.md
- tests/data/html/example_05.html
- tests/test_backend_html.py
- Parse HTML files without `body` tag, since it is optional in [HTML5 specification](https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission)
- Add tests to ensure docling converts HTML documents without the `body` tag
Resolves #810 
**Checklist:**
> fix: parse html with omitted body tag

- docs/examples/backend_xml_rag.ipynb
A small addition for commit 4df08bec32b4f98a45c14ae758e0989c13891a03 after remark https://github.com/DS4SD/docling/pull/788#discussion_r1928347300 from @vagenas 
> Since TEMP_DIR is anyway defined as temporary directory (i.e. will be removed upon restart), this part can also be dropped for simplicity (and to avoid any accidents with folder deletions..)
> docs(backend XML): do not delete temp file in notebook

- README.md
- docs/index.md
- docs/supported_formats.md
- docs/usage.md
- mkdocs.yml
Also:
- factored out and expanded supported formats
- reorged feature list
**Checklist:**
> docs: document Docling JSON parsing

- docling/datamodel/document.py
`filetype` library may not identify some files as PDF, for instance https://github.com/user-attachments/files/18533486/WMOOS6EVZZXGYSVQPP7UORUTNEUEBO3Q.pdf.
As a simple solution, we can leverage `_DocumentConversionInput._mime_from_extension` function and the file extension, following the current pattern with other MIME types. 
Resolves DS4SD/docling#798
**Checklist:**
> fix: use file extension if filetype fails with PDF

- docling/backend/mspowerpoint_backend.py
- docling/backend/msword_backend.py
- docs/faq.md
PIL supports WMF images only on Windows platform, hence this fix
Resolves #594 
**Checklist:**
> fix: Fix for the crash when encountering WMF images in pptx and docx

- docling/backend/html_backend.py
Resolves #849
Resolves #846
**Checklist:**
> fix: use new add_code in html backend and add more typing hints

- docling/backend/msword_backend.py
SDT stands for Structured Document Tag. These are content controls in Word—special containers that can hold specific types of content, often used for forms or metadata.
Resolves #627 
**Checklist:**
> feat(docx): Support of SDTs in docx backend

- docling/datamodel/document.py
- docling/datamodel/settings.py
- docling/document_converter.py
- docling/pipeline/base_pipeline.py
- tests/test_input_doc.py
- tests/test_options.py
> feat: Add option to define page range

- docling/backend/mspowerpoint_backend.py
This PR fixes a crash on pptx files that use placeholder shapes.
When placeholder shape with text is encountered, text is extracted and bounding box of parent slide is used for provenance.
Resolves #584 
**Checklist:**
> fix: Processing of placeholder shapes in pptx that have text but no bbox

- docling/backend/md_backend.py
- tests/data/groundtruth/docling_v2/mixed.md.md
- tests/data/groundtruth/docling_v2/word_tables.docx.html
- tests/data/md/mixed.md
> fix(markdown): add support for HTML content

- docling/backend/msword_backend.py
**Description:**  
**fix(msword_backend):** Handle conversion error in label parsing
Updated the label parsing logic to use `str_to_int` with a default value, preventing potential conversion errors when unexpected formats are encountered.
**Steps to Reproduce:**  
The issue can be reproduced using the attached document, which contains a paragraph style: *"Shell title: Table and Figure"*.
**Code to Reproduce:**
```python
from docling.document_converter import DocumentConverter
converter = DocumentConverter()
_ = converter.convert("issue_paragraph_style.docx")
```
**Attachment:**  
[issue_paragraph_style.docx](https://github.com/user-attachments/files/18672491/issue_paragraph_style.docx)
---
**PS:** Thank you for this excellent package!
---
**Checklist:**
---
> fix(msword_backend): handle conversion error in label parsing

- docling/models/code_formula_model.py
- docling/models/document_picture_classifier.py
- docling/models/layout_model.py
- docling/models/table_structure_model.py
Make sure to use the full `repo_id` in the downloaded artifacts.
We use the same semantics of HF: `org--name`.
**Checklist:**
> refactor: use org--name in artifacts-path

- docling/models/easyocr_model.py
- docling/models/picture_description_api_model.py
`httpx` is imported and not used
Resolves #918
**Checklist:**
> fix: remove unused httpx

- docling/datamodel/settings.py
- docling/pipeline/standard_pdf_pipeline.py
Having `DOCLING_ARTIFACTS_PATH` as environment variable would allow the offline downstream usage without any additional code change.
For example, this could set in containers and all the implementation code doesn't have to take extra care of setting it in the pipeline options, or make a custom logic for it.
**Checklist:**
> feat: allow artifacts_path to be defined as ENV

- tests/test_backend_csv.py
- tests/test_backend_msexcel.py
- tests/test_backend_msword.py
- tests/test_backend_pptx.py
- tests/verify_utils.py
Instead of verifying the exact string match in JSON, this PR introduces the `verify_docitems()` with specialized logic for some specific type of items.
For example, we don't compare exact match in bbox and avoid exact-byte check on PIL images.
**Checklist:**
> test: validate actual docitems in tests

- docling/datamodel/pipeline_options.py
- docling/models/easyocr_model.py
- docling/utils/accelerator_utils.py
- docs/examples/run_with_accelerator.py
This PR is WIP enables the allocation of cuda devices as the current implementation defaults to cuda:0. This enables launching on multi-gpu and not being restricted on cluster systems with device allocation. 
**Note: Further investigation is needed to make easyocr work with cuda:n as easyocr when using GPU it wraps the models in torch.DataParallel, which causes cuda:0 to be utilised.**
> feat: Support cuda:n GPU device allocation

- tests/test_backend_csv.py
- tests/test_backend_html.py
- tests/test_backend_jats.py
- tests/test_backend_msexcel.py
- tests/test_backend_msword.py
- tests/test_backend_pptx.py
- tests/verify_utils.py
The main context of this PR is solving issue #1022, the CSV backend tests is validating the exact JSON.  
- Update tests for CSV backends to avoid testing exact JSON comparisons.  
- Refactor `verify_export` to use `pathlib`.  
- Reuse the new `verify_export` function in tests.  
**Checklist:**
> test: avoid testing exact JSON in CSV backend

- docling/backend/html_backend.py
- tests/data/groundtruth/docling_v2/example_06.html.itxt
- tests/data/groundtruth/docling_v2/example_06.html.json
- tests/data/groundtruth/docling_v2/example_06.html.md
- tests/data/groundtruth/docling_v2/wiki_duck.html.itxt
- tests/data/groundtruth/docling_v2/wiki_duck.html.json
- tests/data/groundtruth/docling_v2/wiki_duck.html.md
- tests/data/html/example_06.html
The HTML backend parses an HTML document and builds `DoclingDocument` elements for certain tags. In particular, `TextItem` elements with label `paragraph` for paragraphs defined with the `<p>` tag.
Even though the `<div>` tag is meant to wrap elements and it has no special meaning, it is common to find text within those tags representing text paragraphs. Currently, docling would ignore that text.
This PR includes the feature to parse text enclosed in `<div>` tags.
Resolves #1019 
**Checklist:**
> fix(html): Parse text in div elements as TextItem

- docs/concepts/chunking.md
- docs/faq.md
> docs: extend chunking docs, add FAQ on token limit

- docling/cli/models.py
- docling/models/picture_description_vlm_model.py
- docling/utils/model_downloader.py
Fix the usage of the artifacts path for the vlm models.
This PR might supersede #1051.
**Checklist:**
> fix: vlm using artifacts path

- docling/backend/html_backend.py
- tests/test_backend_html.py
This PR is about leveraging the `start` attribute in HTML `<ol>` tags (ordered lists) when parsing HTML documents.
In HTML documents, items in ordered lists are always parsed using numbers starting with 1 followed by a period as markers. The export to markdown is therefore simplified, since this notation correspond to the basic syntax in markdown.
However HTML allows ordered lists to start with another number, if indicated by the attribute `start`. Even though the markdown basic syntax recommend to always start with the number 1, applications like GitHub Flavored Markdown usually accept other starting numbers.
In this PR, the HTML backend creates ordered lists starting with the number indicated in `start` attribute, if it exists.
Resolves #1058 …
> fix(html): use 'start' attribute when parsing ordered lists from HTML docs

- .github/workflows/checks.yml
Refs #959 
Use GitHub action cache.
**Checklist:**
> chore: use gh cache for huggingface models

- docling/backend/html_backend.py
- tests/data/groundtruth/docling_v2/example_07.html.itxt
- tests/data/groundtruth/docling_v2/example_07.html.json
- tests/data/groundtruth/docling_v2/example_07.html.md
- tests/data/html/example_07.html
As shown in the example from issue #1117 , some HTML pages may contain embedded lists where a list is a child of another list, instead of a child of another list item. These cases may result in a `KeyError` exception due to a mishandling of the indentation counter.
This PR addresses the cases above, fixes the bug, and adds an example for the regression tests.
Resolves #1117 
**Checklist:**
> fix(html): handle nested empty lists

- docling/backend/msword_backend.py
- tests/data/groundtruth/docling_v2/unit_test_headers_numbered.docx.itxt
- tests/data/groundtruth/docling_v2/unit_test_headers_numbered.docx.json
- tests/data/groundtruth/docling_v2/unit_test_headers_numbered.docx.md
This PR identifies numbered headers in docx documents. This addresses issue https://github.com/docling-project/docling/issues/1212.
**Checklist:**
> fix(docx): identifying numbered headers

- docling/models/page_preprocessing_model.py
**Description:**
Resolved https://github.com/docling-project/docling/issues/1219 issue. 
Discovered that the `PdfTextCell` object was missing the `bbox` attribute/method during testing of the batch conversion functionality within the examples.
Resolution:
*   Renamed `bbox` to `to_bounding_box` and changed the code of line 66 in models\page_preprocessing_model.py file.
**Checklist:**
> fix: Edit bbox to to_bounding_box in PdfTextCell

- docling/backend/html_backend.py
- docling/backend/md_backend.py
- tests/data/groundtruth/docling_v2/mixed_without_h1.md.md
- tests/data/groundtruth/docling_v2/wiki_duck.html.itxt
- tests/data/groundtruth/docling_v2/wiki_duck.html.json
- tests/data/groundtruth/docling_v2/wiki_duck.html.md
- tests/data/md/mixed_without_h1.md
- tests/test_backend_html.py
Primary bug being addressed:
During HTML parsing (which BTW is also triggered by Markdown parsing when HTML elements are present), in case there were headings (`<h*>` tags) but no `<h1>` tags, all content was being marked as furniture.
Now the heuristic is being adapted so that:
- 🆕 if any heading is present (regardless of level h1, h2 etc.), the first one of them marks the beginning of the body; before that it's furniture
- else, i.e. if no headings are present at all, all content is marked as body
Markdown fixes:
- properly propagate section header levels
- improve handling of list subroots without text
> fix: improve HTML layer detection, various MD fixes

- docling/models/table_structure_model.py
Afer latest update, when using backend that supports word-level cells, but at the same time using OCR - tableformer received empty text for cells as @KapyGenius noticed. This PR fixes the issue.
**Checklist:**
> fix: Fixes tables when using OCR

- docling/pipeline/standard_pdf_pipeline.py
Fixes the bug #1333 (also fixes #1193 which is a duplicate of my bug, sorry about that)
**Checklist:**
> fix: Properly address page in pipeline _assemble_document when page_range is provided

- docling/datamodel/document.py
This resolves an issue for me where it won't convert `.xlsx` files even though the readme advertises this. It's just a problem with recognizing the format. Without this change, the `filetype` library resolves it to `application/zip`. Once it gets past this check, it seems to work great.
I'm not super happy with the code of this change, but I don't feel like digging through the repo to figure out the right way to do it. Here's a bug and a fix.
**Checklist:**
- [n/a] Documentation has been updated, if necessary.
- [n/a] Examples have been added, if necessary.
> fix: auto-recognize .xlsx, .docx and .pptx files

- .github/workflows/pypi.yml
Switch to the trusted publisher method and attach signed attestations.
Refs #1374 
**Checklist:**
> ci: sign pypi packages

- docs/installation/index.md
Adds documentation entry for the OnnxTR OCR plugin
ref.: [docling-OCR-OnnxTR](https://github.com/felixdittrich92/docling-OCR-OnnxTR)
Overrides #1222 
Resolves #1209 
**Checklist:**
> docs(ocr): Add docs entry for OnnxTR OCR plugin

- docs/concepts/architecture.md
Changed the usage link in the tip box from "../usage.md#adjust-pipeline-features" to "../usage/index.md#adjust-pipeline-features"  as the previous link is not valid.
> docs: Updated the [Usage] link in architecture.md

- docling/cli/main.py
Fixes: #1417 
This is how most software handles it. Users dont always know how many verbosity levels there are 
**Checklist:**
> fix: Treat overflowing -v flags as DEBUG

- docs/concepts/docling_document.md
Fixes some small typos in the doc.
**Checklist:**
> docs: Typo fixes in docling_document.md

- docs/examples/minimal_vlm_pipeline.py
**Checklist:**
fix: wrong output format in example code
The output format in example code (minimal_vlm_pipeline.py) is wrong, written to `.md` as it shoud be `.json`.
This PR fix that.
> docs: Fix wrong output format in example code

- docling/backend/html_backend.py
- tests/data/groundtruth/docling_v2/example_06.html.itxt
- tests/data/groundtruth/docling_v2/example_06.html.json
- tests/data/groundtruth/docling_v2/example_06.html.md
- tests/data/html/example_06.html
The  [address](https://www.w3schools.com/tags/tag_address.asp) and [details](https://www.w3schools.com/tags/tag_details.asp) are standard tags of the HTML specification. They can be found in the html `body` and their content is typically rendered by browsers.
Docling was omitting those tags, but they could easily be handled like paragraphs.
In this PR, `address` content is parsed in a `TextItem`, like any `p` tag. The `details` tag, including its embedded `summary` tag, is handled by creating a new group and attaching its content, typically as `TextItem` elements.
Resolves #1406
**Checklist:**
> fix(html): handle address, details, and summary tags

- docling/models/table_structure_model.py
By default, value for `do_cell_matching = True`, and it should remain this way, as it works great with new PDF backend, etc.
However indeed we had a bug when `do_cell_matching = False`
This tiny PR, as suggested by @stestagg, fixes this issue in case someone needs it.
Resolves #1453 
**Checklist:**
> fix: Incorrect scaling of TableModel bboxes when do_cell_matching is False

- docling/models/readingorder_model.py
Updated the time-recorder label for reading order: `glm` -> `reading_order`
> fix: updated the time-recorder label for reading order

- docling/models/picture_description_vlm_model.py
This PR ensures the `cuda_use_flash_attention2` flag is respected when using the `PictureDescriptionVlmModel`.
Resolves #1495
**Checklist:**
> fix: enable cuda_use_flash_attention2 for PictureDescriptionVlmModel

- docling/models/tesseract_ocr_model.py
This moves the initialization of the `reader` and `script_readers` attributes to before we attempt to import tesserocr, so that when later accessing these attributes in the garbage collection method `__del__` the attributes exist.
This requires changing the typing of the `script_readers` dict value to `Any` because we cannot yet reference its actual strong type, since it's a tesserocr value.
This prevents throwing an exception during garbage collection for cases where the TesseractOcrModel instance didn't properly initialize, like when it throws an `ImportError` during its initializer.
Resolves #1493
> fix: Guard against attribute errors in TesseractOcrModel __del__

- docling/models/tesseract_ocr_model.py
This is a follow-up to #1494
https://peps.python.org/pep-0563/
> chore: restore typing hint for self.script_readers

- docling/document_converter.py
- docling/utils/utils.py
Since we don't rely on hashes for credentials and security, we should use the option `usedforsecurity=False` to facilitate FIPS use cases.
**Checklist:**
> fix: usage of hashlib for FIPS

- docs/integrations/data_prep_kit.md
The links were broken, since the repository was renamed. I also noticed that PDF2Parquet is now referred to as Docling2Parquet.
> docs: update links in data_prep_kit

- docling/backend/asciidoc_backend.py
Fix regular expression to identify header lines in AsciiDoc avoiding to match defined blocks.
Resolves #1562 
**Checklist:**
> fix: AsciiDoc header identification (#1562)

- docling/models/tesseract_ocr_cli_model.py
Issue resolved by this Pull Request: #1552
> fix(ocr): orig field in TesseractOcrCliModel as str

- docling/backend/docling_parse_backend.py
- docling/backend/docling_parse_v2_backend.py
- docling/backend/docling_parse_v4_backend.py
- docling/utils/layout_postprocessor.py
- Fix ZeroDivisionError when the bbox.area() is zero.
- Make the implementation consistent by the usage of BoundingBox method, `intersection_over_self`.
> fix: fix ZeroDivisionError for cell_bbox.area()

- docling/datamodel/document.py
- tests/test_input_doc.py
This PR improves the heuristic rule to detect the file type from the first section of its content. In particular, the function `docling.datamodel.document._DocumentConversionInput._detect_html_xhtml`.
Even though the HTML5 specification recommends HTML documents to start with `<!DOCTYPE html>`, some documents may have other HTML indicators like <html> or <head> at the beginning of the content.
Some documents may start with scripts (tag `<script>`), like in https://hometheaterhifi.com/reviews/headphone-earphone/hifiman-he1000-unveiled-planar-magnetic-headphone-review/. This PR addresses these cases.
Resolves #1535 
**Checklist:**
> fix: guess HTML content starting with script tag

- docs/index.md
Hello,
Just fixing a typo I found in the webpage.
> docs: fix typo in index.md

- docling/datamodel/base_models.py
I think https://github.com/docling-project/docling/pull/1415 missed this.
See also: https://github.com/docling-project/docling-serve/pull/214
**Checklist:**
> fix: Add WEBP to the list of image file extensions

- docling/datamodel/pipeline_options_vlm_model.py
- docling/models/vlm_models_inline/hf_transformers_model.py
Once we get a few more running experience, we could set the `torch_dtype` automatically when flash_attention is activated. For the moment, let's make sure users can experiment with the correct setting of their choice.
Resolves #1730
**Checklist:**
> fix: allow custom torch_dtype in vlm models

- docling/models/base_model.py
- tests/test_code_formula.py
When page_range param is used for formula conversion, the system throws list index out of range error.
> fix: formula conversion with page_range param set

- docling/datamodel/base_models.py
- docling/datamodel/pipeline_options_vlm_model.py
- docling/models/api_vlm_model.py
- docling/models/vlm_models_inline/hf_transformers_model.py
- docling/models/vlm_models_inline/mlx_model.py
Image scale moved to base vlm options.
Added max_size image limit (options and vlm models processing).
**Context**
Some models like OlmOcr require images to have exact max size.
With this PR the default behavior kept unchanged. But if VlmModel options `max_size` is set, max image size will never be larger than it. Moreover, if someone set scale > max_size, image will be resized to max_size always.
Resolves #1595
**Checklist:**
P.S.
Please advise which of these points should be done for this PR
> feat: Maximum image size for Vlm models

- docling/backend/msword_backend.py
- tests/data/groundtruth/docling_v2/unit_test_formatting.docx.itxt
- tests/data/groundtruth/docling_v2/unit_test_formatting.docx.json
- tests/test_backend_msword.py
This PR ensures that `DoclingDocument` list items are only created as children of a list (`OrderedList` or `UnorderedList`).
Resolves #1780 
**Checklist:**
> fix(docx): ensure list items have a list parent

- docling/backend/msword_backend.py
Small change to handle missing runs, which avoids the out of range exception on some docx files.
Resolves #1681
**Checklist:**
- [ x] Documentation has been updated, if necessary.
- [x ] Examples have been added, if necessary.
- [x ] Tests have been added, if necessary.
> fix: Handle missing runs to avoid out of range exception

- docling/backend/msexcel_backend.py
Traverse cells in table bound finding by `Worksheet.cell` is low efficiency.
**Checklist:**
> perf(msexcel): _find_table_bounds use iter_rows/iter_cols instead of Worksheet.cell

- docling/models/document_picture_classifier.py
- docling/pipeline/standard_pdf_pipeline.py
- tests/test_document_picture_classifier.py
This PR is upgrading the picture classifier enrichment model to the "backend implementation". Effectively, it allows to run the convert a document with the enrichment active without the need to keep all page images in memory.
**Checklist:**
> fix: use only backend for picture classifier

- docs/installation/index.md
On RHEL the tesseract osd is installed as separate package, docs where missing it.
**Checklist:**
> fix: docs are missing osd packages for tesseract on RHEL

- docling/datamodel/pipeline_options.py
- docling/utils/layout_postprocessor.py
Adds an option in layout postprocessing to allow empty clusters propagate the DoclingDocument output.
```
pipeline_options.layout_options.keep_empty_clusters = True # default is False.
```
**Checklist:**
> feat: Add option to control empty clusters in layout postprocessing

- docling/backend/html_backend.py
- tests/data/groundtruth/docling_v2/pntd.0008301.nxml.json
- tests/data/groundtruth/docling_v2/pone.0234687.nxml.json
- tests/data/groundtruth/docling_v2/wiki_duck.html.json
- tests/data/groundtruth/docling_v2/wiki_duck.html.md
The HTML backend parses the text of table cells by concatenating all the child strings, leveraging the `PageElement.get_text()` function. While this works for most cases, if table cells contain different paragraphs (with tag `<p>`), the resulting text may lead to a misrepresentation of the original data. For instance, `<p>a</p><p>b</p>` within a table cell would result in `ab`. The same situation applies when list items are included in table cells.
This PR addresses the case above, by adding a blank space when paragraphs and list items are encountered.
In addition, the PR also removes leading and trailing whitespace characters from the parsed table cell text.
Resolves #1927 
**Checklist:**
> fix(HTML): concatenation of child strings in table cells and list items

- docling/backend/html_backend.py
This PR removes an unnecessary `print` command in the HTML backend.
Resolves #1987 
**Checklist:**
> fix(HTML): remove an unnecessary print command

- docling/backend/html_backend.py
- tests/data/groundtruth/docling_v2/example_09.html.json
- tests/data/groundtruth/docling_v2/example_09.html.md
- tests/data/groundtruth/docling_v2/mixed.md.md
- tests/data/groundtruth/docling_v2/wiki_duck.html.itxt
- tests/data/groundtruth/docling_v2/wiki_duck.html.json
- tests/data/groundtruth/docling_v2/wiki_duck.html.md
- tests/test_backend_html.py
This PR removes or replaces common problematic or non-standard Unicode characters that often appear in HTML. They are mostly non-visible and related to formatting, but they may introduce noise in text processing tasks like tokenization.
More details are described in the corresponding issue
Resolves #2004 
**Checklist:**
> fix(HTML): replace non-standard Unicode characters

- docling/models/vlm_models_inline/mlx_model.py
- pyproject.toml
- uv.lock
When using SmolDocling on Darwin, docling suggests installing mlx-vlm via "pip install mlx-vlm", rather than suggesting installing "docling[vlm]". The latter would install the project specified mlx-vlm<0.2 rather than the latest 0.3.2. As of version 3.0.0 (specifically [this commit](https://github.com/Blaizzy/mlx-vlm/commit/4bf3a3cbf6e857edd15f70fba6281607720fc171)) mlx-vlm no longer provides stream_generate in the mlx_vlm.utils module, leading to [this runtime error](https://github.com/docling-project/docling/issues/1968). Importing stream_generate from the top-level instead of mlx_vlm.utils fixes the issue with the latest mlx-vlm. Alternatively if keeping the specified mlx_vlm version is desired, perhaps docling could be more specific with the mlx-vlm installation suggestion.
> fix: support new mlx-vlm module 

- docling/backend/html_backend.py
<!-- STEPS TO FOLLOW:
1. Fix ValueError Exception when colspan or raw span include a number followed by a string (such as 2;aligh="left")
**Checklist:**
> fix(html): Parse rawspan and colspan when they include non numerical values

- docling/datamodel/pipeline_options_vlm_model.py
- docling/models/api_vlm_model.py
- docling/models/vlm_models_inline/hf_transformers_model.py
- docling/models/vlm_models_inline/mlx_model.py
- docs/examples/vlm_pipeline_api_model.py
This is the third and i hope the last PR to support models like OlmOcr ( 1 - https://github.com/docling-project/docling/pull/1802 , 2 - https://github.com/docling-project/docling/pull/1808 ).
VLM models may generate something more than just text or markdown.
E.g.:
* OlmOcr generates json with information about page language, rotation and recognized text
* Nanonets-OCR-s generates recognized text as markdown, but tables and some other elements as HTML.
For such models we need a way to decode vlm response (fully convert it to markdown).
**Checklist:**
> feat(vlm): Ability to preprocess VLM response

- docling/backend/html_backend.py
This PR fixes a bug that appeared after merging #2131 , related to the HTML backend.
Resolves #2137 
**Checklist:**
> fix(html): access to variable not yet declared

- tests/data/groundtruth/docling_v2/2203.01017v2.json
- tests/data/groundtruth/docling_v2/2203.01017v2.md
- tests/data/groundtruth/docling_v2/2206.01062.json
- tests/data/groundtruth/docling_v2/2305.03393v1-pg9.json
- tests/data/groundtruth/docling_v2/2305.03393v1.json
- tests/data/groundtruth/docling_v2/amt_handbook_sample.json
- tests/data/groundtruth/docling_v2/code_and_formula.json
- tests/data/groundtruth/docling_v2/multi_page.json
- tests/data/groundtruth/docling_v2/picture_classification.json
- tests/data/groundtruth/docling_v2/redp5110_sampled.json
- tests/data/groundtruth/docling_v2/right_to_left_01.json
- tests/data/groundtruth/docling_v2/right_to_left_02.json
- tests/data/groundtruth/docling_v2/right_to_left_03.json
- uv.lock
Test updates:
1. `docling-core` now exports single-row tables
2. document schema number and features in the json exports
```
Updated boto3-stubs v1.40.27 -> v1.40.30
Updated botocore-stubs v1.40.27 -> v1.40.30
Updated compressed-tensors v0.10.2 -> v0.11.0
Updated docling-core v2.48.0 -> v2.48.1
Added frozendict v2.4.6
Updated hf-xet v1.1.9 -> v1.1.10
Updated langchain-core v0.3.75 -> v0.3.76
Updated lm-format-enforcer v0.10.12 -> v0.11.3
Updated mistral-common v1.8.4 -> v1.8.5
Updated mlx v0.29.0 -> v0.29.1
Updated mlx-metal v0.29.0 -> v0.29.1
Updated mypy v1.17.1 -> v1.18.1
Updated nvidia-cublas-cu12 v12.6.4.1, v12.8.4.1 -> v12.8.4.1
Updated nvidia-cuda-cupti-cu12 v12.6.80, v12.8.90 -> v12.8.90
Updated nvidia-cuda-nvrtc-cu12 v12.6.77, v12.8.93 -> v12.8.93
Updated nvidia-cuda-runtime-cu12 …
```
> chore: update lock

- docling/datamodel/pipeline_options.py
- docling/models/rapid_ocr_model.py
- tests/test_e2e_ocr_conversion.py
Add support for additional parameters in RapidOcrOptions and fix the font_path parameter for RapidOCR.
previously it was rec.font_path but now it has to be Global.font_path
**Checklist:**
> feat(RapidOcr): Support generic extra arguments for RapidOcr
